-- MySQL Script generated by MySQL Workbench
-- dom 28 ene 2018 20:35:54 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulance` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ulance` ;

-- -----------------------------------------------------
-- Table `ulance`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulance`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `ulance`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulance`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulance`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ulance`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `primerapellido` VARCHAR(255) NULL,
  `segundoapellido` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `pass` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `tipousuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipousuario_idx` (`tipousuario_id` ASC),
  CONSTRAINT `fk_usuario_tipousuario`
    FOREIGN KEY (`tipousuario_id`)
    REFERENCES `ulance`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulance`.`banco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulance`.`banco` ;

CREATE TABLE IF NOT EXISTS `ulance`.`banco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulance`.`cuentabancaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulance`.`cuentabancaria` ;

CREATE TABLE IF NOT EXISTS `ulance`.`cuentabancaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iban` VARCHAR(255) NULL,
  `banco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuenta_banco1_idx` (`banco_id` ASC),
  CONSTRAINT `fk_cuenta_banco1`
    FOREIGN KEY (`banco_id`)
    REFERENCES `ulance`.`banco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulance`.`cuentaasociada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulance`.`cuentaasociada` ;

CREATE TABLE IF NOT EXISTS `ulance`.`cuentaasociada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `usuario_id` INT NOT NULL,
  `cuentabancaria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuentaasociada_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_cuentaasociada_cuenta1_idx` (`cuentabancaria_id` ASC),
  CONSTRAINT `fk_cuentaasociada_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ulance`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuentaasociada_cuenta1`
    FOREIGN KEY (`cuentabancaria_id`)
    REFERENCES `ulance`.`cuentabancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulance`.`categoriamovimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulance`.`categoriamovimiento` ;

CREATE TABLE IF NOT EXISTS `ulance`.`categoriamovimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulance`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulance`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `ulance`.`movimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(255) NULL,
  `cantidad` MEDIUMTEXT NULL,
  `fecha` DATETIME NULL,
  `categoriamovimiento_id` INT NOT NULL,
  `cuentabancaria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimiento_tipomovimiento1_idx` (`categoriamovimiento_id` ASC),
  INDEX `fk_movimiento_cuenta1_idx` (`cuentabancaria_id` ASC),
  CONSTRAINT `fk_movimiento_tipomovimiento1`
    FOREIGN KEY (`categoriamovimiento_id`)
    REFERENCES `ulance`.`categoriamovimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_cuenta1`
    FOREIGN KEY (`cuentabancaria_id`)
    REFERENCES `ulance`.`cuentabancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
